[package]
name = "gpo-insight"
version = "0.1.6"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = {version = "4.5.4", features = ["derive"]}
console = "0.15.8"
dirs = "5.0.1"
encoding_rs = "0.8.34"
encoding_rs_io = "0.1.7"
html2text = "0.12.5"
lazy_static = "1.4.0"
